import { state } from './state.js';
import { PLATFORMS } from './platforms.js';
import { toast } from './ui.js';
import { txrTrackEvent, txrLogSearchEvent, txrTrackTool } from './analytics.js';
import { updateStrength } from './insights.js';
import { renderHL } from './util.js';

function saveHist(str,url){const keys=[...state.selPlatforms];const item={id:Date.now(),platforms:keys,platformLabel:keys.map(k=>PLATFORMS[k].label).join('+'),tc:PLATFORMS[keys[0]].tc,jobTitles:state.titleBubbles.join(' / '),titleLogic:document.getElementById('titleLogicMode')?.value||'OR',altTitles:state.titleBubbles.slice(1).join(', '),seniority:state.seniorityBubbles.join(', '),mustSkills:state.mustBubbles.map(b=>b.text).join(', '),niceSkills:state.orBubbles.map(b=>typeof b==='string'?b:b.text).join(', '),location:state.locBubbles.join(', '),companies:state.compBubbles.join(', '),exclude:state.excBubbles.join(', '),str,url,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})};state.searchHistory.unshift(item);if(state.searchHistory.length>20)state.searchHistory=state.searchHistory.slice(0,20);localStorage.setItem('txr_history',JSON.stringify(state.searchHistory));renderHistory();}
function reuseSearch(id){const item=state.searchHistory.find(h=>h.id===id);if(!item)return;state.curStr=item.str;state.curUrl=item.url;state.selPlatforms=new Set(item.platforms||[item.platform]);document.querySelectorAll('.platform-btn').forEach(b=>b.classList.toggle('active',state.selPlatforms.has(b.dataset.platform)));document.getElementById('liRow').classList.toggle('hidden',!state.selPlatforms.has('linkedin'));const el=document.getElementById('outputStr');el.innerHTML=renderHL(item.str);el.classList.add('has-content');document.getElementById('outputDot').classList.add('live');document.getElementById('resultsCard').classList.add('live');document.getElementById('resultsCard').classList.add('active');document.getElementById('outputChars').textContent=`${item.str.length} chars`;updateStrength(item.str);txrTrackTool('history_reused',{query_length:item.str.length,platforms:item.platformLabel||''},{query:item.str,resultUrl:item.url,platforms:item.platformLabel||''});toast('Loaded — click Open in Google','ok');window.scrollTo({top:0,behavior:'smooth'});}
function giveFeedback(id,val){const item=state.searchHistory.find(h=>h.id===id);if(!item)return;item.fb=val;localStorage.setItem('txr_history',JSON.stringify(state.searchHistory));renderHistory();txrTrackEvent('search_feedback',{feedback:val===1?'good':'poor',platforms:item.platformLabel||'',query_length:(item.str||'').length});txrLogSearchEvent('result_feedback',{query:item.str||'',resultUrl:item.url||'',platforms:item.platformLabel||'',feedback:val});toast(val===1?'Thanks for the feedback 👍':'Noted — try fewer AND skills 👎',val===1?'ok':'');}
function deleteHist(id){state.searchHistory=state.searchHistory.filter(h=>h.id!==id);localStorage.setItem('txr_history',JSON.stringify(state.searchHistory));renderHistory();txrTrackTool('history_deleted',{history_count:state.searchHistory.length});}
function clearHist(){state.searchHistory=[];localStorage.setItem('txr_history','[]');renderHistory();txrTrackTool('history_cleared');toast('History cleared','');}
function renderHistory(){const panel=document.getElementById('histPanel');const list=document.getElementById('histList');if(!state.searchHistory.length){panel.classList.remove('show');return;}panel.classList.add('show');list.innerHTML=state.searchHistory.map(item=>`<div class="hist-item"><span class="hist-ptag ${item.tc}">${item.platformLabel}</span><span class="hist-text">${item.str}</span><span class="hist-time">${item.time}</span><div class="hist-feedback"><button class="fb-btn ${item.fb===1?'selected':''}" onclick="giveFeedback(${item.id},1)" title="Good results">👍</button><button class="fb-btn ${item.fb===0?'selected':''}" onclick="giveFeedback(${item.id},0)" title="Poor results">👎</button></div><button class="hist-reuse" onclick="reuseSearch(${item.id})">Reuse</button><button class="hist-del" onclick="deleteHist(${item.id})">×</button></div>`).join('');}

function exportCSV(){if(!state.searchHistory.length){toast('No history to export','err');return;}txrTrackTool('history_exported',{row_count:state.searchHistory.length});const esc=v=>'"'+(v||'').replace(/"/g,'""')+'"';const headers=['Timestamp','Platforms','Job Title','Role Logic','Alt Titles','Seniority','Must-Have Skills','Nice-to-Have Skills','Location','Companies','Exclude','Search String','Google URL'];const rows=state.searchHistory.map(h=>{const ts=new Date(h.id).toLocaleString();return[ts,h.platformLabel,h.jobTitles||'',h.titleLogic||'OR',h.altTitles||'',h.seniority||'',h.mustSkills||'',h.niceSkills||'',h.location||'',h.companies||'',h.exclude||'',h.str,h.url].map(esc).join(',');});const csv=[headers.join(','),...rows].join('\n');try{const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`talentxray_${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();setTimeout(()=>{document.body.removeChild(a);URL.revokeObjectURL(url);},100);toast('CSV exported','ok');}catch(e){toast('Export failed — try in Chrome','err');}}
export { saveHist, reuseSearch, giveFeedback, deleteHist, clearHist, renderHistory, exportCSV };
