import { state } from './state.js';
import { buildString } from './query-builder.js';
import { toast } from './ui.js';
import { renderHL, openUrl, copyToClipboard } from './util.js';
import { txrTrackTool } from './analytics.js';

function txrCopyVariation(i){const v=window._vars&&window._vars[i];if(!v)return;copyToClipboard(v.str).then(()=>{txrTrackTool('variation_copied',{variation_index:i+1,query_length:v.str.length},{query:v.str});toast('Copied','ok');});}
function txrOpenVariation(i){const v=window._vars&&window._vars[i];if(!v)return;txrTrackTool('variation_open',{variation_index:i+1,query_length:v.str.length},{query:v.str,resultUrl:v.url});openUrl(v.url);}
function generateVars(){const{str}=buildString();if(!str){toast('Fill in fields first','err');return;}const altTitles=state.titleBubbles.slice(1);const location=state.locBubbles[0]||'';const andSkills=state.mustBubbles.filter(b=>b.mode==='and');const vars=[];if(andSkills.length>=2){const{str:s,url:u}=buildString({mustBubbles:andSkills.slice(0,2)});if(s)vars.push({label:'Minimal — role + top 2 skills only',str:s,url:u});}if(altTitles.length>0){const{str:s,url:u}=buildString({titles:[altTitles[0],...altTitles.slice(1)]});if(s)vars.push({label:`Alt role focus — "${altTitles[0]}"`,str:s,url:u});}if(state.seniorityBubbles.length>0){const{str:s,url:u}=buildString({seniorities:[]});if(s)vars.push({label:'Without seniority filter',str:s,url:u});}if(location){const{str:s,url:u}=buildString({location:''});if(s)vars.push({label:'Without location — catches unlisted cities',str:s,url:u});}if(andSkills.length>0){const orOnly=state.mustBubbles.map(b=>({...b,mode:'or'}));const{str:s,url:u}=buildString({mustBubbles:orOnly});if(s)vars.push({label:'All skills as OR — widest pool',str:s,url:u});}if(!vars.length){toast('Add more fields to generate variations','err');return;}window._vars=vars;txrTrackTool('variations_generated',{variation_count:vars.length,query_length:str.length},{query:str});const panel=document.getElementById('varPanel');panel.classList.add('show');document.getElementById('varList').innerHTML=vars.map((v,i)=>`<div class="var-item"><div class="var-head"><span class="var-tag">Variation ${i+1} — ${v.label}</span><div class="var-acts"><button class="copy-btn" onclick="txrCopyVariation(${i})">Copy</button><button class="copy-btn" onclick="txrOpenVariation(${i})">Open</button></div></div><div class="var-str">${renderHL(v.str)}</div></div>`).join('');panel.scrollIntoView({behavior:'smooth',block:'nearest'});toast(`${vars.length} variations ready`,'ok');}
export { txrCopyVariation, txrOpenVariation, generateVars };
